/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserAccessRouteImport } from './routes/user-access'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReaderStatusRouteImport } from './routes/reader-status'
import { Route as ReaderHistoryRouteImport } from './routes/reader-history'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MemberRouteImport } from './routes/member'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as StaffPayrollRouteImport } from './routes/staff.payroll'
import { Route as StaffAddRouteImport } from './routes/staff.add'
import { Route as StaffIdRouteImport } from './routes/staff.$id'
import { Route as MembersAddRouteImport } from './routes/members.add'
import { Route as MembersIdRouteImport } from './routes/members.$id'
import { Route as MemberWorkoutRouteImport } from './routes/member.workout'
import { Route as MemberPaymentsRouteImport } from './routes/member.payments'
import { Route as MemberHomeRouteImport } from './routes/member.home'
import { Route as MemberAttendanceRouteImport } from './routes/member.attendance'
import { Route as LeadsAddRouteImport } from './routes/leads.add'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as FinanceRecordRouteImport } from './routes/finance.record'
import { Route as FinancePaymentsRouteImport } from './routes/finance.payments'
import { Route as FinanceDuesRouteImport } from './routes/finance.dues'

const UserAccessRoute = UserAccessRouteImport.update({
  id: '/user-access',
  path: '/user-access',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderStatusRoute = ReaderStatusRouteImport.update({
  id: '/reader-status',
  path: '/reader-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderHistoryRoute = ReaderHistoryRouteImport.update({
  id: '/reader-history',
  path: '/reader-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const StaffPayrollRoute = StaffPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAddRoute = StaffAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => StaffRoute,
} as any)
const StaffIdRoute = StaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffRoute,
} as any)
const MembersAddRoute = MembersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => MembersRoute,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MembersRoute,
} as any)
const MemberWorkoutRoute = MemberWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => MemberRoute,
} as any)
const MemberPaymentsRoute = MemberPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => MemberRoute,
} as any)
const MemberHomeRoute = MemberHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MemberRoute,
} as any)
const MemberAttendanceRoute = MemberAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => MemberRoute,
} as any)
const LeadsAddRoute = LeadsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeadsRoute,
} as any)
const FinanceRecordRoute = FinanceRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => FinanceRoute,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDuesRoute = FinanceDuesRouteImport.update({
  id: '/dues',
  path: '/dues',
  getParentRoute: () => FinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/enrollment': typeof EnrollmentRoute
  '/finance': typeof FinanceRouteWithChildren
  '/hardware': typeof HardwareRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/members': typeof MembersRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/reader-history': typeof ReaderHistoryRoute
  '/reader-status': typeof ReaderStatusRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/user-access': typeof UserAccessRoute
  '/finance/dues': typeof FinanceDuesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/record': typeof FinanceRecordRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/add': typeof LeadsAddRoute
  '/member/attendance': typeof MemberAttendanceRoute
  '/member/home': typeof MemberHomeRoute
  '/member/payments': typeof MemberPaymentsRoute
  '/member/workout': typeof MemberWorkoutRoute
  '/members/$id': typeof MembersIdRoute
  '/members/add': typeof MembersAddRoute
  '/staff/$id': typeof StaffIdRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/payroll': typeof StaffPayrollRoute
  '/finance/': typeof FinanceIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/enrollment': typeof EnrollmentRoute
  '/hardware': typeof HardwareRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/reader-history': typeof ReaderHistoryRoute
  '/reader-status': typeof ReaderStatusRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/user-access': typeof UserAccessRoute
  '/finance/dues': typeof FinanceDuesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/record': typeof FinanceRecordRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/add': typeof LeadsAddRoute
  '/member/attendance': typeof MemberAttendanceRoute
  '/member/home': typeof MemberHomeRoute
  '/member/payments': typeof MemberPaymentsRoute
  '/member/workout': typeof MemberWorkoutRoute
  '/members/$id': typeof MembersIdRoute
  '/members/add': typeof MembersAddRoute
  '/staff/$id': typeof StaffIdRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/payroll': typeof StaffPayrollRoute
  '/finance': typeof FinanceIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/members': typeof MembersIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/enrollment': typeof EnrollmentRoute
  '/finance': typeof FinanceRouteWithChildren
  '/hardware': typeof HardwareRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/members': typeof MembersRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/reader-history': typeof ReaderHistoryRoute
  '/reader-status': typeof ReaderStatusRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/user-access': typeof UserAccessRoute
  '/finance/dues': typeof FinanceDuesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/record': typeof FinanceRecordRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/add': typeof LeadsAddRoute
  '/member/attendance': typeof MemberAttendanceRoute
  '/member/home': typeof MemberHomeRoute
  '/member/payments': typeof MemberPaymentsRoute
  '/member/workout': typeof MemberWorkoutRoute
  '/members/$id': typeof MembersIdRoute
  '/members/add': typeof MembersAddRoute
  '/staff/$id': typeof StaffIdRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/payroll': typeof StaffPayrollRoute
  '/finance/': typeof FinanceIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/enrollment'
    | '/finance'
    | '/hardware'
    | '/leads'
    | '/login'
    | '/member'
    | '/members'
    | '/messages'
    | '/notifications'
    | '/pricing'
    | '/reader-history'
    | '/reader-status'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/user-access'
    | '/finance/dues'
    | '/finance/payments'
    | '/finance/record'
    | '/leads/$id'
    | '/leads/add'
    | '/member/attendance'
    | '/member/home'
    | '/member/payments'
    | '/member/workout'
    | '/members/$id'
    | '/members/add'
    | '/staff/$id'
    | '/staff/add'
    | '/staff/payroll'
    | '/finance/'
    | '/leads/'
    | '/members/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/enrollment'
    | '/hardware'
    | '/login'
    | '/member'
    | '/messages'
    | '/notifications'
    | '/pricing'
    | '/reader-history'
    | '/reader-status'
    | '/reset-password'
    | '/settings'
    | '/user-access'
    | '/finance/dues'
    | '/finance/payments'
    | '/finance/record'
    | '/leads/$id'
    | '/leads/add'
    | '/member/attendance'
    | '/member/home'
    | '/member/payments'
    | '/member/workout'
    | '/members/$id'
    | '/members/add'
    | '/staff/$id'
    | '/staff/add'
    | '/staff/payroll'
    | '/finance'
    | '/leads'
    | '/members'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/enrollment'
    | '/finance'
    | '/hardware'
    | '/leads'
    | '/login'
    | '/member'
    | '/members'
    | '/messages'
    | '/notifications'
    | '/pricing'
    | '/reader-history'
    | '/reader-status'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/user-access'
    | '/finance/dues'
    | '/finance/payments'
    | '/finance/record'
    | '/leads/$id'
    | '/leads/add'
    | '/member/attendance'
    | '/member/home'
    | '/member/payments'
    | '/member/workout'
    | '/members/$id'
    | '/members/add'
    | '/staff/$id'
    | '/staff/add'
    | '/staff/payroll'
    | '/finance/'
    | '/leads/'
    | '/members/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  DashboardRoute: typeof DashboardRoute
  EnrollmentRoute: typeof EnrollmentRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  HardwareRoute: typeof HardwareRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRouteWithChildren
  MembersRoute: typeof MembersRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  ReaderHistoryRoute: typeof ReaderHistoryRoute
  ReaderStatusRoute: typeof ReaderStatusRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRouteWithChildren
  UserAccessRoute: typeof UserAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-access': {
      id: '/user-access'
      path: '/user-access'
      fullPath: '/user-access'
      preLoaderRoute: typeof UserAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader-status': {
      id: '/reader-status'
      path: '/reader-status'
      fullPath: '/reader-status'
      preLoaderRoute: typeof ReaderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader-history': {
      id: '/reader-history'
      path: '/reader-history'
      fullPath: '/reader-history'
      preLoaderRoute: typeof ReaderHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/staff/payroll': {
      id: '/staff/payroll'
      path: '/payroll'
      fullPath: '/staff/payroll'
      preLoaderRoute: typeof StaffPayrollRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/add': {
      id: '/staff/add'
      path: '/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof StaffAddRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$id': {
      id: '/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof StaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/members/add': {
      id: '/members/add'
      path: '/add'
      fullPath: '/members/add'
      preLoaderRoute: typeof MembersAddRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/member/workout': {
      id: '/member/workout'
      path: '/workout'
      fullPath: '/member/workout'
      preLoaderRoute: typeof MemberWorkoutRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/payments': {
      id: '/member/payments'
      path: '/payments'
      fullPath: '/member/payments'
      preLoaderRoute: typeof MemberPaymentsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/home': {
      id: '/member/home'
      path: '/home'
      fullPath: '/member/home'
      preLoaderRoute: typeof MemberHomeRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/attendance': {
      id: '/member/attendance'
      path: '/attendance'
      fullPath: '/member/attendance'
      preLoaderRoute: typeof MemberAttendanceRouteImport
      parentRoute: typeof MemberRoute
    }
    '/leads/add': {
      id: '/leads/add'
      path: '/add'
      fullPath: '/leads/add'
      preLoaderRoute: typeof LeadsAddRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/finance/record': {
      id: '/finance/record'
      path: '/record'
      fullPath: '/finance/record'
      preLoaderRoute: typeof FinanceRecordRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/dues': {
      id: '/finance/dues'
      path: '/dues'
      fullPath: '/finance/dues'
      preLoaderRoute: typeof FinanceDuesRouteImport
      parentRoute: typeof FinanceRoute
    }
  }
}

interface FinanceRouteChildren {
  FinanceDuesRoute: typeof FinanceDuesRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceRecordRoute: typeof FinanceRecordRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceDuesRoute: FinanceDuesRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceRecordRoute: FinanceRecordRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface LeadsRouteChildren {
  LeadsIdRoute: typeof LeadsIdRoute
  LeadsAddRoute: typeof LeadsAddRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsIdRoute: LeadsIdRoute,
  LeadsAddRoute: LeadsAddRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface MemberRouteChildren {
  MemberAttendanceRoute: typeof MemberAttendanceRoute
  MemberHomeRoute: typeof MemberHomeRoute
  MemberPaymentsRoute: typeof MemberPaymentsRoute
  MemberWorkoutRoute: typeof MemberWorkoutRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAttendanceRoute: MemberAttendanceRoute,
  MemberHomeRoute: MemberHomeRoute,
  MemberPaymentsRoute: MemberPaymentsRoute,
  MemberWorkoutRoute: MemberWorkoutRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface MembersRouteChildren {
  MembersIdRoute: typeof MembersIdRoute
  MembersAddRoute: typeof MembersAddRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersIdRoute: MembersIdRoute,
  MembersAddRoute: MembersAddRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface StaffRouteChildren {
  StaffIdRoute: typeof StaffIdRoute
  StaffAddRoute: typeof StaffAddRoute
  StaffPayrollRoute: typeof StaffPayrollRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIdRoute: StaffIdRoute,
  StaffAddRoute: StaffAddRoute,
  StaffPayrollRoute: StaffPayrollRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  DashboardRoute: DashboardRoute,
  EnrollmentRoute: EnrollmentRoute,
  FinanceRoute: FinanceRouteWithChildren,
  HardwareRoute: HardwareRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRouteWithChildren,
  MembersRoute: MembersRouteWithChildren,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  ReaderHistoryRoute: ReaderHistoryRoute,
  ReaderStatusRoute: ReaderStatusRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRouteWithChildren,
  UserAccessRoute: UserAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
